$(document).ready(function () {
    // alert("OK")
    $('#about').click(function () {
        $('.about').addClass('activ')
        $('.essential').removeClass('activ')
        $('.gallery').removeClass('activ')
        $('.review').removeClass('activ')
        $('.price').removeClass('activ')
        $('.round__category').html(`<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, accusamus libero eveniet enim totam officiis ad repudiandae maxime vero quisquam saepe aperiam odio consequuntur facilis neque beatae omnis, repellat natus, cumque illo quis! Nemo culpa nesciunt dolorum, consequatur tempore asperiores alias neque quo natus eos fuga voluptatum impedit vero animi officiis optio recusandae quos, ut delectus quis sequi. Quae magnam atque, molestias dolore, nemo voluptate neque unde alias quod ullam accusamus veritatis dolorum aliquid error facilis harum animi maxime nihil doloremque exercitationem! Debitis ipsam, expedita sint laborum, totam quidem laboriosam assumenda corrupti quae placeat veniam! Sed corrupti nihil aliquam minus.</p>`)
    })
    $('#essential').click(function () {
        $('.essential').addClass('activ')
        $('.about').removeClass('activ')
        $('.gallery').removeClass('activ')
        $('.review').removeClass('activ')
        $('.price').removeClass('activ')
        $('.round__category').html(`<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, accusamus libero eveniet enim totam officiis ad repudiandae maxime vero quisquam saepe aperiam odio consequuntur facilis neque beatae omnis, repellat natus</p>`)
    })
    $('#gallery').click(function () {
        $('.gallery').addClass('activ')
        $('.essential').removeClass('activ')
        $('.about').removeClass('activ')
        $('.review').removeClass('activ')
        $('.price').removeClass('activ')
        $('.round__category').html(`<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, accusamus libero eveniet enim totam officiis ad repudiandae maxime vero quisquam saepe aperiam odio consequuntur facilis neque beatae omnis, repellat natus, cumque illo quis! Nemo culpa nesciunt Debitis ipsam, expedita sint laborum, totam quidem laboriosam assumenda corrupti quae placeat veniam! Sed corrupti nihil aliquam minus.</p>`)
    })
    $('#review').click(function () {
        $('.review').addClass('activ')
        $('.essential').removeClass('activ')
        $('.gallery').removeClass('activ')
        $('.about').removeClass('activ')
        $('.price').removeClass('activ')
        $('.round__category').html(`<p> Lorem ipsum dolor sit amet, consectetur  totam quidem laboriosam assumenda corrupti quae placeat veniam! Sed corrupti nihil aliquam minus.</p>`)
    })
    $('#price').click(function () {
        $('.price').addClass('activ')
        $('.essential').removeClass('activ')
        $('.gallery').removeClass('activ')
        $('.review').removeClass('activ')
        $('.about').removeClass('activ')
        $('.round__category').html(`<p> eat veniam! Sed corrupti nihil aliquam minus.</p>`)
    })
    $('#date').click(function () {
        $('.price').addClass('activ')
        $('.essential').removeClass('activ')
        $('.gallery').removeClass('activ')
        $('.review').removeClass('activ')
        $('.about').removeClass('activ')
        $('.round__category').html(`<p> eat veniam! Sed corrupti nihil aliquam minus.</p>`)
    })
})